web:
  build: .
  command: 'bash -c ''go-websocket-chat-demo-web'''
  working_dir: /app/user/src/github.com/heroku-examples/go-websocket-chat-demo
  environment:
    PORT: 8080
    REDIS_URL: 'redis://herokuRedis:6379'
  ports:
    - '8080:8080'
  links:
    - herokuRedis
shell:
  build: .
  command: bash
  working_dir: /app/user/src/github.com/heroku-examples/go-websocket-chat-demo
  environment:
    PORT: 8080
    REDIS_URL: 'redis://herokuRedis:6379'
  ports:
    - '8080:8080'
  links:
    - herokuRedis
  volumes:
    - '.:/app/user/src/github.com/heroku-examples/go-websocket-chat-demo'
herokuRedis:
  image: redis
