web:
  build: .
  command: 'bash -c ''gowebsocketapp1'''
  working_dir: /app/user/src/github.com/wonseobjoe/gowebsocketapp1
  environment:
    PORT: 8080
    REDIS_URL: 'redis://herokuRedis2:6379'
  ports:
    - '8080:8080'
  links:
    - herokuRedis2
shell:
  build: .
  command: bash
  working_dir: /app/user/src/github.com/wonseobjoe/gowebsocketapp1
  environment:
    PORT: 8080
    REDIS_URL: 'redis://herokuRedis2:6379'
  ports:
    - '8080:8080'
  links:
    - herokuRedis2
  volumes:
    - '.:/app/user/src/github.com/wonseobjoe/gowebsocketapp1'
herokuRedis2:
  image: redis
